name: CI

# Trigger the workflow on push or pull request
on: [ push, pull_request ]

jobs:
  build-check:
    name: "Check: code cleanliness"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check tabs and whitespace
        shell: bash
        run: ".github/workflows/check_whitespace.sh"

  build-ubuntu:
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04 ]
    name: "Build: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install dependencies
        shell: bash
        run: ".github/workflows/install_dependencies_ubuntu.sh"
      - name: Build
        run: "make -j2"
      - name: Smoketest
        run: "make check"
